/******************************************************************
*   Created by LiXingang
*   Description: 
*
******************************************************************/
#ifndef _ULC_HELPER_ID_H
#define _ULC_HELPER_ID_H
#ifdef __cplusplus
extern "C"
{
#endif

enum {
    ULC_ID_MALLOC = 1000001,
    ULC_ID_FREE,
    ULC_ID_VMALLOC,
    ULC_ID_VFREE,
    ULC_ID_REALLOC,
    ULC_ID_MODULE_ALLOC,
    ULC_ID_MODULE_FREE,
    ULC_ID_COPY_FROM_USER,
    ULC_ID_COPY_TO_USER,

    ULC_ID_PRINTF = 1000050,
    ULC_ID_PUTS,
    ULC_ID_SPRINTF,
    ULC_ID_GETC,
    ULC_ID_UNGETC,
    ULC_ID_STRERROR,
    ULC_ID_FTELL,
    ULC_ID_FSEEK,
    ULC_ID_FOPEN,
    ULC_ID_FREAD,
    ULC_ID_FCLOSE = 1000060,
    ULC_ID_FGETS,
    ULC_ID_FWRITE,
    ULC_ID_FREOPEN,
    ULC_ID_FERROR,
    ULC_ID_FEOF,
    ULC_ID_FPUTS,
    ULC_ID_FPUTC,
    ULC_ID_FFLUSH,
    ULC_ID_SETVBUF,
    ULC_ID_CLEARERR = 1000070,
    ULC_ID_FPRINTF,
    ULC_ID_FSCANF,
    ULC_ID_TMPFILE,
    ULC_ID_TMPNAM,

    ULC_ID_STAT = 1000100,
    ULC_ID_ACCESS,
    ULC_ID_LOCALECONV,
    ULC_ID_SETLOCALE,
    ULC_ID_USLEEP,
    ULC_ID_EXIT,

    ULC_ID_GETENV = 1000108,
    ULC_ID_CLOCK,
    ULC_ID_TIME = 1000110,
    ULC_ID_GMTIME,
    ULC_ID_LOCALTIME,
    ULC_ID_MKTIME,
    ULC_ID_STRFTIME,
    ULC_ID_SYSTEM,
    ULC_ID_REMOVE,
    ULC_ID_RENAME,
    ULC_ID_SIGNAL,
    ULC_ID_ABORT,

    ULC_ID_SOCKET = 1000200,
    ULC_ID_BIND,
    ULC_ID_CONNECT,
    ULC_ID_LISTEN,
    ULC_ID_ACCEPT,
    ULC_ID_RECV,
    ULC_ID_SEND,
    ULC_ID_CLOSE,
    ULC_ID_SETSOCKOPT,

    ULC_ID_THREAD_CREATE = 1000300,

    ULC_ID_RCU_CALL = 1000352,
    ULC_ID_RCU_LOCK,
    ULC_ID_RCU_UNLOCK,
    ULC_ID_RCU_SYNC,
    ULC_ID_RCU_BARRIER,

    ULC_ID_ERRNO = 1000402,
    ULC_ID_SETJMP,
    ULC_ID_LONGJMP,
    
    ULC_ID_INIT_TIMER = 1000410,
    ULC_ID_ADD_TIMER,
    ULC_ID_DEL_TIMER,

    ULC_ID_MMAP_MAP = 1000450,
    ULC_ID_MMAP_UNMAP,
    ULC_ID_MMAP_MPROTECT,

    ULC_ID_GET_SYM = 1000470,

    ULC_ID_SET_TRUSTEESHIP = 1000480,
    ULC_ID_GET_TRUSTEESHIP,

    ULC_ID_DO_NOTHING = 1000490,
    ULC_ID_LOCAL_ARCH,
    ULC_ID_SET_HELPER,
    ULC_ID_GET_HELPER,
    ULC_ID_GET_BASE_HELPER,
    ULC_ID_GET_SYS_HELPER,
    ULC_ID_GET_USER_HELPER,
    ULC_ID_ENV_NAME,

    
    ULC_ID_MAP_LOOKUP_ELEM = 1000500,
    ULC_ID_MAP_UPDATE_ELEM,
    ULC_ID_MAP_DELETE_ELEM,
    ULC_ID_MAP_GET_NEXT_KEY,

    
    ULC_ID_RAW_MAP_LOOKUP_ELEM, 
    ULC_ID_RAW_MAP_UPDATE_ELEM,
    ULC_ID_RAW_MAP_DELETE_ELEM,

    ULC_ID_GET_MAP_BY_PATH, 
    ULC_ID_BPF_MAP_PUT,     

    
    ULC_ID_SET_RUNTIME = 1000600,
    ULC_ID_GET_RUNTIME,
    ULC_ID_GET_SELF_NAME, 
    ULC_ID_EVOB_NOTIFY,
    ULC_ID_IDFUNC_RUN,
    ULC_ID_NAMEFUNC_RUN,
};

#ifdef __cplusplus
}
#endif
#endif 
